[build-system]
requires = ["setuptools",
            "setuptools_scm",
            "oldest-supported-numpy",
            "wheel"]
build-backend = 'setuptools.build_meta'

[tool.cibuildwheel]
skip = "cp36-* cp37-*"
