name: Run tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        include:
          # Build in which CASA can be installed
          - os: ubuntu-16.04
            python-version: 3.6
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install testing dependencies
      run: python -m pip install tox codecov
    - name: Run tests with latest stable version of dependencies
      if: ${{ matrix.python-version != '3.9' }}
      run: tox -v -e test
    - name: Run tests with latest developer version of dependencies
      if: ${{ matrix.python-version == '3.9' }}
      run: tox -v -e test-dev
    - name: Run tests with CASA
      if: ${{ matrix.python-version == '3.6' && matrix.os == 'ubuntu-16.04' }}
      run: tox -v -e test-casa
    - name: Reporting coverage to codecov
      run: codecov --file .tmp/*/.coverage
