name: Build and upload to PyPI

on: [push, pull_request]

jobs:
  publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@v1
    with:
      test_extras: test
      test_command: pytest --pyargs casa_formats_io
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
